# Generated by Django 3.2.1 on 2021-05-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooked',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='seatbooked',
            name='seat',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
