# Generated by Django 3.2.1 on 2021-05-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seatbook', '0002_auto_20210508_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatbooked',
            name='user',
        ),
    ]
