# Generated by Django 3.2.1 on 2021-05-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatbook', '0003_remove_seatbooked_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookseat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('SeatsQuantity', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Seatbooked',
        ),
    ]
