# Generated by Django 3.2.1 on 2021-05-21 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seatbook', '0004_auto_20210518_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookseat',
            name='SeatsQuantity',
        ),
        migrations.AddField(
            model_name='bookseat',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookseat',
            name='SeatsCount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookseat',
            name='Ticket_confirm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookseat',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardNumber', models.IntegerField(blank=True, null=True)),
                ('EDate', models.CharField(blank=True, max_length=50, null=True)),
                ('CV', models.IntegerField(blank=True, null=True)),
                ('DCode', models.CharField(blank=True, max_length=50, null=True)),
                ('bookseat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seatbook.bookseat')),
            ],
        ),
    ]
