# Generated by Django 3.2.1 on 2021-05-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custommodel',
            old_name='phone',
            new_name='mobile',
        ),
    ]
