# Generated by Django 3.2.1 on 2021-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newarrival',
            name='Poster',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
