# Generated by Django 3.2.1 on 2021-05-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_newarrival_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('Poster', models.CharField(blank=True, max_length=255, null=True)),
                ('Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Genre', models.CharField(blank=True, max_length=255, null=True)),
                ('Playlogo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
