# Generated by Django 3.2.1 on 2021-05-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_trendposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendposter',
            name='Poster',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
