# Generated by Django 3.2.1 on 2021-05-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_trendposter_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendposter',
            name='Playlogo',
            field=models.ImageField(blank=True, null=True, upload_to='Playlogo/'),
        ),
    ]
