# Generated by Django 3.2.1 on 2021-05-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_bookseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='newarrival',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newarrivalbelow',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='popularshow',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trendposter',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
